export enum GroupChain {
  Aptos = 'aptos',
  Binance = 'binance',
  Ethereum = 'ethereum',
  Linea = 'linea',
  Moonbeam = 'moonbeam',
  Polygon_pos = 'polygon_pos',
  Polygon_zkevm = 'polygon_zkevm',
  Solana = 'solana',
  Sui = 'sui',
  Zeta = 'zeta',
  Sei = 'sei',
  Shardeum = 'shardeum',
  Arbitrum = 'arbitrum',
  Taiko = 'taiko',
  Base = 'base',
  Viction = 'viction',
  Avalanche = 'avalanche',
  Movement = 'movement',
  X1 = 'x1',
  Injective = 'injective',
  Blast = 'blast',
  Bera = 'bera',
  Ancient8 = 'ancient8',
  Fantom = 'fantom',
  Scroll = 'scroll',
  Manta_pacific = 'manta_pacific',
}
