export enum GroupChain {
  Aptos = 'aptos',
  Binance = 'binance',
  Ethereum = 'ethereum',
  Hedera = 'hedera',
  Linea = 'linea',
  Moonbeam = 'moonbeam',
  Polygon_pos = 'polygon_pos',
  Polygon_zkevm = 'polygon_zkevm',
  Solana = 'solana',
  Sui = 'sui',
  Zeta = 'zeta',
  Sei = 'sei',
  Shardeum = 'shardeum',
  Arbitrum = 'arbitrum',
  Taiko = 'taiko',
  Base = 'base',
  Tomo = 'tomo',
}
